/**
 * @datawhale/agent — Event-driven agent runtime
 * 
 * Inspired by @earendil-works/pi-agent-core:
 * - AgentLoop with turn-based execution
 * - Tool calling with parallel execution
 * - Event streaming for UI integration
 * - State management with immutable updates
 */

import type { Message, MessagePart, ToolDef, ToolResultPart } from "@datawhale/ai"
import { chatStream, resolveModel, type ModelConfig } from "@datawhale/ai"
import { SkillStore } from "./skill-store.js"
import type { Skill, SkillMeta } from "./skill-store.js"
import { makeQuery, makeTurn } from "./query-types.js"
import type { Span, Query, ThinkingSpan, ToolCallSpan, TextSpan } from "./query-types.js"

// ─── Types ───────────────────────────────────────────────────────────────────

export type AgentStatus =
  | "idle"
  | "thinking"
  | "acting"
  | "waiting"
  | "done"
  | "error"

export interface AgentConfig {
  /** System prompt for the agent */
  systemPrompt: string
  /** Model to use (alias or provider/model) */
  model: string | ModelConfig
  /** Available tools */
  tools: AgentTool[]
  /** Maximum turns (LLM calls) per run */
  maxTurns?: number
  /** Temperature override */
  temperature?: number
  /** Max tokens per response */
  maxTokens?: number
  /** Called before each turn, can modify messages */
  transformContext?: (messages: AgentMessage[]) => AgentMessage[]
  /** Called before each LLM call to select model dynamically */
  modelRouter?: (messages: AgentMessage[], turn: number) => string | ModelConfig
  /** Called before tool execution */
  beforeToolCall?: (ctx: ToolCallContext) => void | Promise<void>
  /** Called after tool execution */
  afterToolCall?: (ctx: ToolCallResult) => void | Promise<void>
}

export interface AgentTool {
  name: string
  description: string
  parameters: Record<string, unknown> // JSON Schema
  /** Execution mode: parallel allows concurrent execution with other tools */
  executionMode?: "sequential" | "parallel"
  /** Execute the tool. Throw on error, return content on success. */
  execute: (
    toolCallId: string,
    params: Record<string, unknown>,
    signal?: AbortSignal,
    onUpdate?: (update: { content: string }) => void
  ) => Promise<ToolResult>
}

export interface ToolResult {
  content: string
  details?: Record<string, unknown>
  /** Set to true to hint the agent should stop after this batch */
  terminate?: boolean
}

export interface ToolCallContext {
  toolCallId: string
  toolName: string
  args: Record<string, unknown>
  agentState: AgentState
}

export interface ToolCallResult extends ToolCallContext {
  result: ToolResult
  isError: boolean
  errorMessage?: string
}

// ─── Agent Messages ──────────────────────────────────────────────────────────

export interface AgentMessage {
  role: "system" | "user" | "assistant" | "tool_result"
  content: string | MessagePart[]
  timestamp: number
  /** Reasoning/thinking content (DeepSeek V4 thinking mode) */
  thinking?: string
  /** Optional metadata for tracking */
  meta?: Record<string, unknown>
}

export interface AgentState {
  messages: AgentMessage[]
  tools: AgentTool[]
  status: AgentStatus
  turnCount: number
  currentToolCallId?: string
  error?: string
}

// ─── Agent Events ────────────────────────────────────────────────────────────

export type AgentEvent =
  | { type: "agent_start"; state: AgentState }
  | { type: "agent_end"; state: AgentState }
  | { type: "turn_start"; turn: number }
  | { type: "turn_end"; turn: number; toolResults: ToolCallResult[] }
  | { type: "message_start"; message: AgentMessage }
  | { type: "message_update"; delta: string }
  | { type: "reasoning_update"; delta: string }
  | { type: "message_end"; message: AgentMessage }
  | { type: "tool_call_start"; toolCallId: string; toolName: string; args: Record<string, unknown> }
  | { type: "tool_call_progress"; toolCallId: string; content: string }
  | { type: "tool_call_end"; toolCallId: string; result: ToolCallResult }
  | { type: "error"; message: string; recoverable: boolean }
  | { type: "span_delta"; span: Span }
  | { type: "query_end"; query: Query }
  // Artifact events: content generated by agent (HTML, charts, etc.)
  | { type: "artifact_start"; artifactId: string; artifactType: string; title?: string; fileUrl?: string }
  | { type: "artifact_delta"; artifactId: string; delta: string }
  | { type: "artifact_end"; artifactId: string }

// ─── Tool Content Compressor ────────────────────────────────────────────────

/**
 * Compress excessive newlines in tool result content to prevent
 * format contagion — where LLM mimics the high newline density of
 * table/formatted outputs and starts emitting one-word-per-line text.
 * 
 * Preserves table structure (Unicode box-drawing chars) while
 * collapsing unnecessary blank lines in non-table content.
 */
function compressToolContent(content: string): string {
  if (!content || content.length < 50) return content

  // Detect if content contains table formatting (box-drawing characters)
  const hasTable = /[┌┬┐├┼┤└┴┘│]/.test(content)

  if (hasTable) {
    // For table content: preserve structure, but remove consecutive blank lines
    // (3+ newlines → 2 newlines)
    return content.replace(/\n{3,}/g, "\n\n")
  }

  // For non-table content: aggressive newline compression
  // Replace 2+ newlines with a single newline
  let compressed = content.replace(/\n{2,}/g, "\n")

  // Truncate to 3000 chars max to limit context pollution
  if (compressed.length > 3000) {
    compressed = compressed.slice(0, 3000) + `\n... (truncated from ${content.length} chars)`
  }

  return compressed
}

// ─── Agent Class ─────────────────────────────────────────────────────────────

type EventListener = (event: AgentEvent) => void

export class Agent {
  public state: AgentState
  private config: AgentConfig
  private listeners: Set<EventListener> = new Set()
  private abortController: AbortController | null = null
  private _currentSpans: Span[] = []
  private _currentUserContent = ""

  constructor(config: AgentConfig) {
    this.config = {
      maxTurns: 50,
      ...config,
    }
    this.state = {
      messages: [],
      tools: config.tools,
      status: "idle",
      turnCount: 0,
    }
  }

  /** Subscribe to agent events */
  subscribe(listener: EventListener): () => void {
    this.listeners.add(listener)
    return () => this.listeners.delete(listener)
  }

  /** Emit an event to all listeners */
  private emit(event: AgentEvent): void {
    for (const listener of this.listeners) {
      try {
        listener(event)
      } catch {
        // Don't let listener errors break the agent
      }
    }
  }

  /** Send a user prompt and run the agent loop */
  async prompt(userInput: string): Promise<AgentState> {
    this.abortController = new AbortController()

    try {
      this.state = {
        ...this.state,
        status: "thinking",
        turnCount: 0,
        error: undefined,
      }

      // Add user message
      const userMsg: AgentMessage = {
        role: "user",
        content: userInput,
        timestamp: Date.now(),
      }
      this.state = { ...this.state, messages: [...this.state.messages, userMsg] }
      this._currentUserContent = userInput

      this.emit({ type: "agent_start", state: this.state })

      // Main agent loop
      const maxTurns = this.config.maxTurns || 50
      while (this.state.turnCount < maxTurns) {
        const turnResult = await this.runTurn()
        if (turnResult === "stop") break
        if (turnResult === "error") {
          this.state = { ...this.state, status: "error" }
          break
        }
      }

      if (this.state.status !== "error") {
        this.state = { ...this.state, status: "done" }
      }

      // Build and emit Query from collected spans
      const spans = this._currentSpans
      const query = makeQuery({
        sessionId: (this.state.messages[0]?.meta?.sessionId as string) || "",
        userContent: this._currentUserContent,
        model: typeof this.config.model === "string" ? this.config.model : this.config.model.model,
      })
      if (spans.length > 0) {
        query.turns = [makeTurn(spans)]
      }
      this.emit({ type: "query_end", query })
      this._currentSpans = []
      this._currentUserContent = ""

      this.emit({ type: "agent_end", state: this.state })
      return this.state
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      this.state = { ...this.state, status: "error", error: message }
      this.emit({ type: "error", message, recoverable: false })
      this.emit({ type: "agent_end", state: this.state })
      return this.state
    }
  }

  /** Abort the current run */
  abort(): void {
    this.abortController?.abort()
  }

  /** Add a system message */
  addSystemMessage(content: string): void {
    this.state = {
      ...this.state,
      messages: [
        ...this.state.messages,
        { role: "system", content, timestamp: Date.now() },
      ],
    }
  }

  /** Update available tools */
  setTools(tools: AgentTool[]): void {
    this.state = { ...this.state, tools }
  }

  // ─── Private: Turn Loop ─────────────────────────────────────────────────

  private async runTurn(): Promise<"continue" | "stop" | "error"> {
    const turn = this.state.turnCount + 1
    this.state = { ...this.state, turnCount: turn, status: "thinking" }
    this.emit({ type: "turn_start", turn })

    // Build messages for LLM
    let llmMessages = this.buildLlmMessages()

    // Apply context transform if configured
    if (this.config.transformContext) {
      llmMessages = this.config.transformContext(
        llmMessages.filter((m) => m.role !== "system")
      )
    }

    // Build final message list
    const messages: Message[] = [
      { role: "system", content: this.buildSystemPrompt() },
      ...this.toLlmMessages(llmMessages),
    ]

    // Resolve model config — apply router if configured
    let modelSource = this.config.model
    if (this.config.modelRouter) {
      modelSource = this.config.modelRouter(llmMessages, turn)
    }
    const modelConfig =
      typeof modelSource === "string"
        ? resolveModel(modelSource, {
            temperature: this.config.temperature,
            maxTokens: this.config.maxTokens,
          })
        : modelSource

    // Build tool defs for LLM
    const toolDefs: ToolDef[] = this.state.tools.map((t) => ({
      name: t.name,
      description: t.description,
      parameters: t.parameters,
    }))

    // Call LLM with streaming
    let assistantContent: MessagePart[] = []
    let assistantMsg: AgentMessage = {
      role: "assistant",
      content: [],
      timestamp: Date.now(),
    }
    let reasoningContent = ""

    this.emit({ type: "message_start", message: { ...assistantMsg } })

    try {
      for await (const event of chatStream({
        model: modelConfig,
        messages,
        tools: toolDefs.length > 0 ? toolDefs : undefined,
        abortSignal: this.abortController?.signal,
      })) {
        switch (event.type) {
          case "text_delta":
            assistantContent.push({ type: "text", text: event.text })
            assistantMsg = { ...assistantMsg, content: [...assistantContent] }
            this.emit({ type: "message_update", delta: event.text })
            // Append to text span
            var lastTextSpan = this._currentSpans[this._currentSpans.length - 1]
            if (lastTextSpan && lastTextSpan.type === "text") {
              lastTextSpan.content += event.text
            } else {
              this._currentSpans.push({ type: "text", content: event.text, startedAt: Date.now() } as TextSpan)
            }
            break

          case "reasoning_delta":
            reasoningContent += event.text
            this.emit({ type: "reasoning_update", delta: event.text })
            // Append to thinking span
            var lastSpan = this._currentSpans[this._currentSpans.length - 1]
            if (lastSpan && lastSpan.type === "thinking") {
              lastSpan.content += event.text
            } else {
              this._currentSpans.push({ type: "thinking", content: event.text, startedAt: Date.now() } as ThinkingSpan)
            }
            break

          case "tool_call_start":
            assistantContent.push({
              type: "tool_call",
              id: event.id,
              name: event.name,
              arguments: "",
            })
            this.emit({ type: "tool_call_start", toolCallId: event.id, toolName: event.name, args: {} })
            this._currentSpans.push({
              type: "tool_call", id: event.id, name: event.name, arguments: "", isError: false, startedAt: Date.now()
            } as ToolCallSpan)
            break

          case "tool_call_delta":
            // Update the last tool_call part
            const lastPart = assistantContent[assistantContent.length - 1]
            if (lastPart?.type === "tool_call") {
              assistantContent[assistantContent.length - 1] = {
                ...lastPart,
                arguments: lastPart.arguments + event.arguments,
              }
            }
            break

          case "tool_call_end":
            // Update final arguments
            const idx = assistantContent.findIndex(
              (p) => p.type === "tool_call" && p.id === event.id
            )
            if (idx >= 0) {
              assistantContent[idx] = {
                type: "tool_call",
                id: event.id,
                name: event.name,
                arguments: event.arguments,
              }
            }
            this.emit({ type: "tool_call_end", toolCallId: event.id, result: { isError: false, result: { content: "" }, agentState: this.state, toolCallId: event.id, toolName: event.name, args: {} } })
            break

          case "error":
            this.state = { ...this.state, error: event.message }
            this.emit({ type: "error", message: event.message, recoverable: false })
            return "error"

          case "finish":
            if (event.reasoningContent) {
              reasoningContent = event.reasoningContent
            }
            break
        }
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      this.emit({ type: "error", message, recoverable: true })
      return "error"
    }

    // Finalize assistant message
    assistantMsg = { ...assistantMsg, content: assistantContent, thinking: reasoningContent || undefined, meta: reasoningContent ? { reasoningContent } : undefined }
    this.state = {
      ...this.state,
      messages: [...this.state.messages, assistantMsg],
    }
    this.emit({ type: "message_end", message: assistantMsg })

    // Extract tool calls
    const toolCalls = assistantContent.filter(
      (p): p is { type: "tool_call"; id: string; name: string; arguments: string } =>
        p.type === "tool_call"
    )

    if (toolCalls.length === 0) {
      // No tool calls → agent is done
      this.emit({ type: "turn_end", turn, toolResults: [] })
      return "stop"
    }

    // Execute tools
    this.state = { ...this.state, status: "acting" }
    const toolResults = await this.executeTools(toolCalls)

    // Add tool results to messages
    for (const tr of toolResults) {
      const rawContent = tr.isError ? `Error: ${tr.errorMessage}` : tr.result.content
      // Compress newline density to prevent format contagion in LLM output
      const compressedContent = compressToolContent(rawContent)
      const toolResultMsg: AgentMessage = {
        role: "tool_result",
        content: [
          {
            type: "tool_result",
            toolCallId: tr.toolCallId,
            content: compressedContent,
            isError: tr.isError,
          } as MessagePart,
        ],
        timestamp: Date.now(),
        // Preserve tool details (e.g. artifact data) for persistence
        meta: tr.result.details ? { details: tr.result.details } : undefined,
      }
      this.state = {
        ...this.state,
        messages: [...this.state.messages, toolResultMsg],
      }
    }

    this.emit({ type: "turn_end", turn, toolResults })

    // Check if all tools want to terminate
    const allTerminate = toolResults.every((tr) => tr.result.terminate)
    if (allTerminate && toolResults.length > 0) {
      return "stop"
    }

    return "continue"
  }

  // ─── Private: Tool Execution ────────────────────────────────────────────

  private async executeTools(
    toolCalls: Array<{ type: "tool_call"; id: string; name: string; arguments: string }>
  ): Promise<ToolCallResult[]> {
    const results: ToolCallResult[] = []

    // Group tools by execution mode
    const sequential: typeof toolCalls = []
    const parallel: typeof toolCalls = []

    for (const tc of toolCalls) {
      const toolDef = this.state.tools.find((t) => t.name === tc.name)
      if (toolDef?.executionMode === "sequential") {
        sequential.push(tc)
      } else {
        parallel.push(tc)
      }
    }

    // Execute sequential tools one at a time
    for (const tc of sequential) {
      const result = await this.executeSingleTool(tc)
      results.push(result)
    }

    // Execute parallel tools concurrently
    if (parallel.length > 0) {
      const parallelResults = await Promise.all(
        parallel.map((tc) => this.executeSingleTool(tc))
      )
      results.push(...parallelResults)
    }

    return results
  }

  private async executeSingleTool(
    toolCall: { type: "tool_call"; id: string; name: string; arguments: string }
  ): Promise<ToolCallResult> {
    const toolDef = this.state.tools.find((t) => t.name === toolCall.name)
    let args: Record<string, unknown> = {}

    try {
      args = JSON.parse(toolCall.arguments)
    } catch {
      return {
        toolCallId: toolCall.id,
        toolName: toolCall.name,
        args: {},
        result: { content: "" },
        isError: true,
        errorMessage: `Failed to parse tool arguments: ${toolCall.arguments}`,
        agentState: this.state,
      }
    }

    this.emit({
      type: "tool_call_start",
      toolCallId: toolCall.id,
      toolName: toolCall.name,
      args,
    })

    // Run beforeToolCall hook
    if (this.config.beforeToolCall) {
      await this.config.beforeToolCall({
        toolCallId: toolCall.id,
        toolName: toolCall.name,
        args,
        agentState: this.state,
      })
    }

    if (!toolDef) {
      const result: ToolCallResult = {
        toolCallId: toolCall.id,
        toolName: toolCall.name,
        args,
        result: { content: "" },
        isError: true,
        errorMessage: `Unknown tool: ${toolCall.name}`,
        agentState: this.state,
      }
      this.emit({ type: "tool_call_end", toolCallId: toolCall.id, result })
      // Update tool_call span with result
      for (var si = this._currentSpans.length - 1; si >= 0; si--) {
        var s = this._currentSpans[si]
        if (s.type === "tool_call" && (s as ToolCallSpan).id === toolCall.id) {
          var tcSpan = s as ToolCallSpan
          tcSpan.result = result.result.content
          tcSpan.isError = result.isError
          tcSpan.completedAt = Date.now()
          break
        }
      }
      return result
    }

    try {
      const toolResult = await toolDef.execute(
        toolCall.id,
        args,
        this.abortController?.signal,
        (update) => {
          this.emit({
            type: "tool_call_progress",
            toolCallId: toolCall.id,
            content: update.content,
          })
        }
      )

      const result: ToolCallResult = {
        toolCallId: toolCall.id,
        toolName: toolCall.name,
        args,
        result: toolResult,
        isError: false,
        agentState: this.state,
      }

      // Run afterToolCall hook
      if (this.config.afterToolCall) {
        await this.config.afterToolCall(result)
      }

      this.emit({ type: "tool_call_end", toolCallId: toolCall.id, result })
      return result
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err)
      const result: ToolCallResult = {
        toolCallId: toolCall.id,
        toolName: toolCall.name,
        args,
        result: { content: "" },
        isError: true,
        errorMessage,
        agentState: this.state,
      }

      if (this.config.afterToolCall) {
        await this.config.afterToolCall(result)
      }

      this.emit({ type: "tool_call_end", toolCallId: toolCall.id, result })
      return result
    }
  }

  // ─── Private: Message Building ──────────────────────────────────────────

  private buildSystemPrompt(): string {
    let prompt = this.config.systemPrompt

    // Add available data context if tools include database access
    const hasDbTools = this.state.tools.some((t) =>
      ["list_tables", "query", "describe_table", "get_schema"].includes(t.name)
    )
    if (hasDbTools) {
      prompt += `\n\nYou have access to database tools. Always explore the data structure before querying.`
    }

    // Add tool list to system prompt
    if (this.state.tools.length > 0) {
      prompt += `\n\nAvailable tools:`
      for (const tool of this.state.tools) {
        prompt += `\n- ${tool.name}: ${tool.description}`
      }
    }

    return prompt
  }

  private buildLlmMessages(): AgentMessage[] {
    let messages = this.state.messages

    // Apply transform if configured
    if (this.config.transformContext) {
      messages = this.config.transformContext(messages)
    }

    return messages
  }

  private toLlmMessages(agentMessages: AgentMessage[]): Message[] {
    return agentMessages
      .filter((m) => m.role === "user" || m.role === "assistant" || m.role === "tool_result")
      .map((m) => {
        if (m.role === "tool_result") {
          const parts = Array.isArray(m.content) ? m.content : []
          const toolResult = parts.find((p) => p.type === "tool_result")
          return {
            role: "tool" as const,
            content: m.content,
            toolCallId: toolResult?.toolCallId,
          }
        }
        return {
          role: m.role as "user" | "assistant",
          content: m.content,
          reasoningContent: m.meta?.reasoningContent as string | undefined,
        }
      }) as Message[]
  }
}

// ─── Shared Knowledge Extraction ──────────────────────────────────────────

/**
 * Extract structured knowledge facts from conversation messages.
 * 
 * This is the canonical knowledge extraction pipeline shared by CLI and
 * app-server. It takes raw LLM output (the JSON array text) and handles
 * parsing + storage. The caller is responsible for calling the LLM with
 * the extracted summary; this function only handles the post-LLM phase.
 * 
 * See also: `buildKnowledgeSummary` for generating the LLM prompt input.
 */
export async function ingestKnowledgeJson(
  rawJsonText: string,
  sessionId: string,
  store: KnowledgeStore,
): Promise<number> {
  if (!rawJsonText || rawJsonText.length < 3) return 0

  // Strip markdown code fences
  let clean = rawJsonText.replace(/```json\s*/gi, "").replace(/```\s*/g, "").trim()

  let entries: Array<{ domain: string; fact: string; keywords: string }> = []

  // Try array format: [...]
  const arrayMatch = clean.match(/^\s*\[([\s\S]*)\]\s*$/)
  if (arrayMatch) {
    try { entries = JSON.parse(arrayMatch[0]) } catch { /* fall through */ }
  }

  // Fallback: single object {...}
  if (entries.length === 0) {
    const objMatch = clean.match(/^\s*\{[\s\S]*\}\s*$/)
    if (objMatch) {
      try { const obj = JSON.parse(objMatch[0]); entries = [obj] } catch { /* fall through */ }
    }
  }

  // Last-resort: find any JSON array anywhere in text
  if (entries.length === 0) {
    const anyMatch = clean.match(/\[[\s\S]*\]/)
    if (anyMatch) {
      try { entries = JSON.parse(anyMatch[0]) } catch { /* fall through */ }
    }
  }

  let added = 0
  for (const entry of entries) {
    if (entry.fact && entry.fact.length > 5) {
      await store.add({
        domain: entry.domain || "general",
        fact: entry.fact,
        keywords: entry.keywords || "",
        sourceSession: sessionId,
        createdAt: Date.now(),
        confidence: 0.6,
      })
      added++
    }
  }

  return added
}

/**
 * Build a plain-text summary of a conversation suitable as the user-content
 * input for an LLM-based knowledge extraction prompt.
 */
export function buildKnowledgeSummary(messages: AgentMessage[]): string {
  const userMsgs = messages.filter((m) => m.role === "user")
  const assistantMsgs = messages.filter((m) => m.role === "assistant")
  if (userMsgs.length === 0 || assistantMsgs.length === 0) return ""

  return messages
    .filter((m) => m.role === "user" || m.role === "assistant")
    .map((m) => {
      const text =
        typeof m.content === "string"
          ? m.content
          : (Array.isArray(m.content)
              ? m.content
                  .filter((p: any) => p.type === "text")
                  .map((p: any) => p.text)
                  .join(" ")
              : "")
      return `[${m.role}]: ${text.slice(0, 300)}`
    })
    .join("\n")
}

/**
 * Standard system prompt for knowledge extraction via LLM.
 */
export const KNOWLEDGE_EXTRACTION_SYSTEM_PROMPT = `CRITICAL: Output ONLY a JSON array, no other text, no markdown formatting, no explanations.

From the conversation below, extract 1-3 key facts about the data that would be valuable for future sessions. Focus on:
- Data schema (table names, column meanings, data types)
- Business semantics (what values mean, domain knowledge)
- Data quality observations (patterns, anomalies, edge cases)

Format: [{"domain":"...","fact":"...","keywords":"keyword1,keyword2"}]

Example response (this is the ONLY format you should output):
[{"domain":"sales","fact":"The region column contains values: East, West, North, South","keywords":"region,sales,geography"}]

DO NOT include any text before or after the JSON array.`

// ─── Re-exports ───────────────────────────────────────────────────────────────

export { SessionStore } from "./session-store.js"
export type { SessionMeta } from "./session-store.js"
export { TraceStore } from "./trace-store.js"
export type { TraceRecord } from "./trace-store.js"
export { KnowledgeStore } from "./knowledge-store.js"
export type { KnowledgeEntry } from "./knowledge-store.js"
export { SkillStore } from "./skill-store.js"
export type { Skill, SkillMeta } from "./skill-store.js"
export type { Message, MessagePart, ToolDef, ModelConfig }
export { QueryStore } from "./query-store.js"
export type { Query, Span, ThinkingSpan, ToolCallSpan, TextSpan } from "./query-types.js"
export { makeQuery } from "./query-types.js"
export { getDatabase, saveDatabase, releaseDatabase, poolSize } from "./db-pool.js"
